version: "2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    logging:
      driver: none

  kafka-broker:
    build: .
    #image: dylanmei/kafka:0.10.1.0
    ports:
      - 9092:9092
      - 8778:8778
    environment:
      KAFKA_OPTS: -javaagent:/usr/jolokia/agents/jolokia-jvm.jar=host=0.0.0.0
      KAFKA_HEAP_OPTS: -Xmx1G -Xms1G
      KAFKA_JVM_PERFORMANCE_OPTS: -server -XX:+UseG1GC -XX:MaxGCPauseMillis=25 -XX:InitiatingHeapOccupancyPercent=35 -XX:+DisableExplicitGC -Djava.awt.headless=true
    depends_on: [zookeeper]

  # Jolokia2 input is based on this PR:
  # https://github.com/influxdata/telegraf/pull/2278
  telegraf:
    image: quay.io/nordstrom/telegraf:1.3.4-1
    environment:
      JOLOKIA_ADDR: "kafka-broker:8778"
      http_proxy: ""
      https_proxy: ""
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
