version: "2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  broker:
    build: .
    ports:
      - 9092:9092
    depends_on: [zookeeper]
